### importing libraries 

In [1]:
import numpy as np
import pandas as pd

### reading dataset

In [2]:
data=pd.read_csv("atm_dataset.csv")

In [3]:
data=data.head()
data

step      type    amount     nameOrig  oldbalanceOrg  newbalanceOrig  \
0     1   PAYMENT   9839.64  C1231006815       170136.0       160296.36   
1     1   PAYMENT   1864.28  C1666544295        21249.0        19384.72   
2     1  TRANSFER    181.00  C1305486145          181.0            0.00   
3     1  CASH_OUT    181.00   C840083671          181.0            0.00   
4     1   PAYMENT  11668.14  C2048537720        41554.0        29885.86   

      nameDest  oldbalanceDest  newbalanceDest  isFraud  isFlaggedFraud  
0  M1979787155               0             0.0        0               0  
1  M2044282225               0             0.0        0               0  
2   C553264065               0             0.0        1               0  
3    C38997010           21182             0.0        1               0  
4  M1230701703               0             0.0        0               0

In [4]:
X=data.iloc[:,[2,4,5,7,8]].values
X

array([[  9839.64, 170136.  , 160296.36,      0.  ,      0.  ],
       [  1864.28,  21249.  ,  19384.72,      0.  ,      0.  ],
       [   181.  ,    181.  ,      0.  ,      0.  ,      0.  ],
       [   181.  ,    181.  ,      0.  ,  21182.  ,      0.  ],
       [ 11668.14,  41554.  ,  29885.86,      0.  ,      0.  ]])

In [5]:
y=data.iloc[:,-2].values
y

array([0, 0, 1, 1, 0], dtype=int64)

### splitting values into training and testing values

In [6]:
from sklearn.model_selection import train_test_split

In [7]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.4,random_state=42)

In [8]:
X_train

array([[   181.  ,    181.  ,      0.  ,      0.  ,      0.  ],
       [  9839.64, 170136.  , 160296.36,      0.  ,      0.  ],
       [   181.  ,    181.  ,      0.  ,  21182.  ,      0.  ]])

In [9]:
y_train

array([1, 0, 1], dtype=int64)

In [10]:
X_test

array([[ 1864.28, 21249.  , 19384.72,     0.  ,     0.  ],
       [11668.14, 41554.  , 29885.86,     0.  ,     0.  ]])

In [11]:
y_test

array([0, 0], dtype=int64)

### training the model

In [12]:
from sklearn.linear_model import LinearRegression

In [13]:
reg=LinearRegression()

In [14]:
reg.fit(X_train,y_train)

LinearRegression()

### prediction : features = [type, amount, oldbalanceOrg, newbalanceOrig]

In [15]:
y_pred=reg.predict(X_test)

In [16]:
y_pred

array([0.87737675, 0.78173666])

In [17]:
features=np.array([[9000000,1000,10000,0,0]])
#features = np.array([[4, 9000.60, 9000.60, 0.0]])
val=reg.predict(features)
if val>0:
    print('success')
else:
    print('fraud')

fraud


In [18]:
features=np.array([[900,1000,10000,0,0]])
#features = np.array([[4, 9000.60, 9000.60, 0.0]])
val=reg.predict(features)
if val>0:
    print('success')
else:
    print('fraud')

success


In [19]:
features=np.array([[1500,1000,100000000,0,0]])
val=reg.predict(features)
if val>0:
    print('success')
else:
    print('fraud')

fraud
